#!/bin/bash

#//******************************//#
#//# Author: by uriid1		#//#
#//# license: GNU GPL		#//#
#//# telegram: uriid1		#//#
#//# Mail: appdurov@gmail.com	#//#
####****************************####

# Константы
version="1.0.2"
c_yellow='\033[1;33m'
c_green='\033[1;32m'
c_def='\033[0m'

# Изменяемые переменные
u_w=1080
u_h=1080

# Пользовательская  Ширина/Высота
case $4 in
	-w | --width)
		u_w=$5
		echo $u_w
esac

case $6 in
	-h | --height)
		u_h=$7
		echo $u_h
esac


#
clear
echo -e "${c_green} Inst by uriid1 ${c_def} | ${c_yellow} version: $version ${c_def} \n"

# Удаляем пробелы в именах
list_format=(jpg png JPG PNG jpeg)
for i in ${list_format[@]}
do
	find ./ -maxdepth 1 -type f -name "* *.$i" -exec bash -c 'mv "$0" "${0// /_}"' {} \;
done

# Функция конвертирования изображения
convert_image() {
	
	# Получаем ширину и высоту изображений
	read pw ph < <(convert "$FILE" -format "%w %h" info:)
	
	# соотношение сторон
	ratio=$(bc -l <<< "$pw/$ph")
	
	if [ $pw -gt $ph ];
	then
		# Новая высота относительно новой ширины
		new_width=$((u_w - border))
		new_height=$(bc -l <<< "$new_width/$ratio")
	else
		# Новая ширина относительно новой высоты
		new_height=$((u_h - border))
		new_width=$(bc -l <<< "$new_height*$ratio")
	fi
	
	# Расположение по центру
	PX=$(bc -l <<< "($u_w-$new_width)/2")
	PY=$(bc -l <<< "($u_h-$new_height)/2")
	
	# Рисуем картинку
	NAME="$DIRSTACK/inst_${FILE##*/}"
	convert -size $u_w"x"$u_h xc:white \
	  -draw "image over  $PX,$PY $new_width,$new_height '$FILE'" \
	  $NAME
	  echo "finished: ${NAME##*/} "
}

# Проверка для первого аргумента
case $1 in
	-a | --all)
		# Обработка всех изображений
		# Рамка
		border=$2
		echo -e " Framing: "$border"px \n Width: $u_w""px"" \n Height: $u_h""px"" \n"
		
		# Для всех
		for FILE in $(find -maxdepth 1 -type f -regextype posix-extended -iregex ".*\.(jpg|png|JPG|PNG|jpeg)$")
		do
			convert_image
		done
		;;
	-o | --one)
		# Обработка одного изображения
		FILE=$2
		
		# Рамка
		border=$3
		echo -e " Framing: "$border"px \n Width: $u_w""px"" \n Height: $u_h""px"" \n"
		
		convert_image
		;;
	*)
		echo
		echo "The parameters are set incorrectly!"
		exit 0
esac
