#!/bin/bash

# Programm name
pname='inst'

# Install
chmod +x $pname
sudo cp inst /usr/bin

# Check
if [ -e /usr/bin/$pname ]
then
	echo "$pname installed successfully!"
else
	echo -e "You may have entered the wrong password. \n Either $pname is already installed."
fi
